[package]
name = "race"
version = "0.1.0"
authors = ["Maximilian Fricke <mfricke2808@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.12"
termion = "1.5"
libc = "0.2"
clap = "2.32"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
